### ISSUE TITLE
chore: move back to node-rpc-docs.celestia.org

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1118]
```[tasklist]
### Tasks
- [ ] remove instructions in readme
- [ ] remove old openrpc-*.json files
- [ ] remove api pages
- [ ] add back link to homepage of node-rpc-docs.celestia.org which will load the latest version always
```
