### ISSUE TITLE
Tracking EPIC for documentation

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1180]
```[tasklist]
### Improvements
- [ ] https://github.com/celestiaorg/docs/pull/1188
- [ ] https://github.com/celestiaorg/docs/pull/1191
- [ ] #1170
```

```[tasklist]
### Documentation
- [ ] #1134
- [ ] #11
- [ ] #79
- [ ] #61
- [ ] #80
- [ ] #244
- [ ] #1100
- [ ] #988
- [ ] #1054
- [ ] #1094
- [ ] #1120
- [ ] #1132
- [ ] #1092
```

```[tasklist]
### Workflow & CI
- [ ] https://github.com/celestiaorg/docs/pull/1181
- [ ] #116
- [ ] #1059
- [ ] #1071
- [ ] #1104
```

```[tasklist]
### Style & graphics
- [ ] #1173
- [ ] https://github.com/celestiaorg/docs/pull/1182
- [ ] https://github.com/celestiaorg/docs/pull/1189
- [ ] #1171
- [ ] https://github.com/celestiaorg/docs/issues/1187
- [ ] #1178
- [ ] #1177
- [ ] #981
- [ ] https://github.com/celestiaorg/docs/issues/1193
```

```[tasklist]
### Standardization
- [ ] https://github.com/celestiaorg/docs/issues/1199
- [ ] #1076
```

```[tasklist]
### External to documentation
- [ ] #989
- [ ] https://github.com/celestiaorg/docs/issues/1183
- [ ] https://github.com/celestiaorg/docs/issues/1201
```

**Comment by jcstein** [comment]
closing as this just makes things more confusing for me.
