### ISSUE TITLE
docs: audit current state of Optimism docs and update based on latest release notes

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1509]
```[tasklist]
### Tasks
- [x] audit the docs, comparing them to the release notes https://github.com/celestiaorg/optimism/releases/tag/v1.2.0-OP_v1.7.2-CN_v0.13.2
- [x] remove local-celestia-devnet versions
- [x] DA specific changes moved to https://github.com/celestiaorg/op-plasma-celestia
- [x] make default to deploy with mocha
- [x] eth fallback could be removed, finding data is relevant
- [x] Josh to revise the Optimism documentation to minimize the content footprint by removing information about local devnets and focusing solely on deploying with Mocha, streamlining the deployment process and removing any redundant or unnecessary steps, and redirecting users to Rollup-as-a-Service (RaaS) providers if they want to deploy a rollup.
- [x] for docs, we can link to the readme:  https://github.com/celestiaorg/op-plasma-celestia?tab=readme-ov-file#using-rollop
- [x] add link to prerequisites https://github.com/0xFableOrg/roll-op?tab=readme-ov-file#prerequisites before running roll-op
- [x] Which uses which uses our fork of roll-op:  https://github.com/celestiaorg/roll-op
- [x] `python3 -m venv ./venv source ./venv/bin/activate`
- [x] 1. sync light node, provide TIA to it 2. start roll-op up
- [x] note to use HA ethereum RPC provider if needed
- [x] `deploy_slowly = true`
```
