### ISSUE TITLE
docs: updates for nitro

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/docs#1587]
```[tasklist]
### Tasks
- [x] update contract addresses
- [x] update links to new version
- [x] change prefix to 0x63
- [x] remove websocket connections for batch poster
- [x] config changes: rm: is-poster, event-channel-size; validator optional, needs tmint rpc; poster no longer needs special stuff
- [x] add configurable fallback to anytrust, other DA, etc. this is helpful if you plan on having high throughput and cannot fall back to ETH because blobs are too big
- [x] 3.0.0 enables stylus - add on overview page 058fc1e9
- [x] blobstream x happens when there is a fraud proof. if there is fraud, whoever submitted the fraud proof has to submit another proof that contains proof the batch data was committed to by Blobstream
- [x] add da server for celestia-node - WIP by Diego
- [ ] update deployment portal after new contracts are ready
- [ ] review contract addresses
```

**Comment by jcstein** [comment]
moved a task not critical to this PR to a new issue #1627

**Comment by jcstein** [comment]
thank you again @Ferret-san. resolved in #1955
